age/urls.py
from django.urls import path, include
from . import views
from .views import SignUpView,SignupComplete
from django.conf import settings
from django.conf.urls.static import static

app_name = 'age'

urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('', views.index.as_view(),name="index"),
    #新規登録
    path('signup',views.SignUpView.as_view(),name='signup'),
    path('complete',views.SignupComplete,name='complete'),
    #家具
    path('list/', views.FurnListView.as_view(),name="list"),
    path('furndetail/<int:pk>/', views.FurnDetailView.as_view(),name="furndetail"),
    path('furnhistory/<int:num>/', views.furnhistory,name="furnhistory"),
    path('furnimage/<int:num>/', views.furnimage,name="furnimage"),
    path('furnhistoryupd/<int:pk>/', views.FurnHistoryupdView.as_view(),name="furnhistoryupd"),
    path('furncreate/',views.furncreate,name="furncreate"),
    path('furndelete/<int:pk>/', views.FurnDeleteView.as_view(),name="furndelete"),
    path('furnupdate/<int:pk>/', views.furnupdate,name="furnupdate"),
    #家電
    path('homeelecdetail/<int:pk>/', views.HomeelecDetailView.as_view(),name="homeelecdetail"),
    path('elechistory/<int:num>/', views.elechistory,name="elechistory"),
    path('elecimage/<int:num>/', views.elecimage,name="elecimage"),
    path('elechistoryupd/<int:pk>/', views.ElecHistoryupdView.as_view(),name="elechistoryupd"),
    path('homeeleccreate/', views.eleccreate,name="homeeleccreate"),
    path('homeelecdelete/<int:pk>/', views.HomeelecDeleteView.as_view(),name="homeelecdelete"),
    path('homeelecupdate/<int:pk>/', views.elecupdate,name="homeelecupdate"),
    #記念日
    path('anivdetail/<int:pk>/', views.AnnivDetailView.as_view(),name="anivdetail"),
    path('anivhistory/<int:num>/', views.anivhistory,name="anivhistory"),
    path('anivimage/<int:num>/', views.anivimage,name="anivimage"),
    path('anivhistoryupd/<int:pk>/', views.AnivHistoryupdView.as_view(),name="anivhistoryupd"),
    path('anivcreate/', views.anivcreate,name="anivcreate"),
    path('anivdelete/<int:pk>/', views.AnnivDeleteView.as_view(),name="anivdelete"),
    path('anivupdate/<int:pk>/', views.anivupdate,name="anivupdate"),
    #ファッション
    path('fashiondetail/<int:pk>/', views.ClothesDetailView.as_view(),name="fashiondetail"),
    path('fashionhistory/<int:num>/', views.clothhistory,name="fashionhistory"),
    path('fashionimage/<int:num>/', views.clothimage,name="fashionimage"),
    path('fashionhistoryupd/<int:pk>/', views.ClothHistoryupdView.as_view(),name="fashionhistoryupd"),
    path('fashioncreate/', views.clothcreate,name="fashioncreate"),
    path('fashiondelete/<int:pk>/', views.ClothesDeleteView.as_view(),name="fashiondelete"),
    path('fashionupdate/<int:pk>/', views.clothupdate,name="fashionupdate"),
    #その他
    path('otherdetail/<int:pk>/', views.OtherDetailView.as_view(),name="otherdetail"),
    path('otherhistory/<int:num>/', views.otherhistory,name="otherhistory"),
    path('otherimage/<int:num>/', views.otherimage,name="otherimage"),
    path('otherhistoryupd/<int:pk>/', views.OtherHistoryupdView.as_view(),name="otherhistoryupd"),
    path('othercreate/', views.othercreate,name="othercreate"),
    path('otherdelete/<int:pk>/', views.OtherDeleteView.as_view(),name="otherdelete"),
    path('otherupdate/<int:pk>/', views.otherupdate,name="otherupdate"),
    #ギャラリー
    path('gallery/', views.GalleryView.as_view(),name="gallery"),
    path('webhook/', views.webhook, name='webhook'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("age.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

age/forms.py
import bootstrap_datepicker_plus as datetimepicker
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import CustomUser,Furn, HomeElecApp,Aniversary,Clothes,Other,ElecHistory,FurnHistory,AnivHistory,ClothHistory,OtherHistory,FurnImage,ElecImage,AnivImage,ClothImage,OtherImage

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username','email','birthday','gender',)
class ElecForm(forms.ModelForm):
    class Meta:
        model = HomeElecApp
        fields = ['name','category','story','birthday','favorite','picture1']
class ElecupdForm(forms.ModelForm):
    class Meta:
        model = HomeElecApp
        fields = ['name','category','story','favorite','picture1']
class FurnForm(forms.ModelForm):
    class Meta:
        model = Furn
        fields = ['name','story','birthday','favorite','picture1']
class FurnupdForm(forms.ModelForm):
    class Meta:
        model = Furn
        fields = ['name','story','favorite','picture1']
class AnivForm(forms.ModelForm):
    class Meta:
        model = Aniversary
        fields = ['annivapp','story','didday','favorite','picture1']
class AnivupdForm(forms.ModelForm):
    class Meta:
        model = Aniversary
        fields = ['annivapp','story','favorite','picture1']
class OtherForm(forms.ModelForm):
    class Meta:
        model = Other
        fields = ['name','category','story','birthday','favorite','picture1']
class OtherupdForm(forms.ModelForm):
    class Meta:
        model = Other
        fields = ['name','category','story','favorite','picture1']
class ClothForm(forms.ModelForm):
    class Meta:
        model = Clothes
        fields = ['name','category','story','birthday','favorite','picture1']
class ClothupdForm(forms.ModelForm):
    class Meta:
        model = Clothes
        fields = ['name','category','story','favorite','picture1']
class ElecHistoryForm(forms.ModelForm):
    class Meta:
        model = ElecHistory
        fields = ['history1','historyday1']
class FurnHistoryForm(forms.ModelForm):
    class Meta:
        model = FurnHistory
        fields = ['history1','historyday1']
class AnivHistoryForm(forms.ModelForm):
    class Meta:
        model = AnivHistory
        fields = ['history1','historyday1']
class ClothHistoryForm(forms.ModelForm):
    class Meta:
        model = ClothHistory
        fields = ['history1','historyday1']
class OtherHistoryForm(forms.ModelForm):
    class Meta:
        model = OtherHistory
        fields = ['history1','historyday1']
class ElecImageForm(forms.ModelForm):
    class Meta:
        model = ElecImage
        fields = ['picture']
class FurnImageForm(forms.ModelForm):
    class Meta:
        model = FurnImage
        fields = ['picture']
class AnivImageForm(forms.ModelForm):
    class Meta:
        model = AnivImage
        fields = ['picture']
class ClothImageForm(forms.ModelForm):
    class Meta:
        model = ClothImage
        fields = ['picture']
class OtherImageForm(forms.ModelForm):
    class Meta:
        model = OtherImage
        fields = ['picture']
class LoginForm(auth_forms.AuthenticationForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

age/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic import TemplateView, ListView,DetailView,CreateView,DeleteView,UpdateView
from .models import Furn,HomeElecApp,Aniversary,Other,Clothes,FurnHistory,ElecHistory,AnivHistory,ClothHistory,OtherHistory,FurnImage,ElecImage,AnivImage,ClothImage,OtherImage,CustomUser
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy,reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm,ElecForm,ElecupdForm,FurnForm,FurnupdForm,AnivForm,AnivupdForm,OtherForm,OtherupdForm,ClothForm,ClothupdForm,ElecHistoryForm,FurnHistoryForm,AnivHistoryForm,ClothHistoryForm,OtherHistoryForm,ElecImageForm,FurnImageForm,AnivImageForm,ClothImageForm,OtherImageForm,LoginForm
from django.http import HttpResponse,HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
import schedule
import time
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from linebot.models import (
    FollowEvent, TextSendMessage,MessageEvent,TextMessage ,ImageMessage, AudioMessage
)
import os
from django.views import generic
from . import models
import requests
import json
from itertools import chain
from django.contrib.auth.views import LoginView, LogoutView
df=0
with open('age/key.json') as f:
    df = json.load(f)
webhook_url = df["webhook_url"]
print(df)
main_content = {
  "content": "起動しました"
}
requests.post(webhook_url,main_content)
def job():
    now = datetime.date.today()
    for i in chain(HomeElecApp.objects.all(),Other.objects.all(),Clothes.objects.all(),Furn.objects.all()):
        elecage = i.birthday
        print(elecage)
        if now.day == elecage.day: #今日が誕生日！！！！！！
            main_content = {
                "content": "今日は" + str(i.name) + "の誕生日です！"
            }
            requests.post(webhook_url,main_content)
    for i in Aniversary.objects.all():
        anivage = i.didday
        print(anivage)
        if now.day == anivage.day: #今日が誕生日！！！！！！
            main_content = {
                "content": "今日は" + str(i.annivapp) + "です！"
            }
            requests.post(webhook_url,main_content)
User=get_user_model()
noticeuser = User.objects.get(pk=1)
ntctime = str(noticeuser.noticetime)
print(ntctime)
schedule.every().day.at(ntctime).do(job)
class index(TemplateView):
    template_name = "age/index.html"
class MyLoginView(LoginView):
    form_class = LoginForm
    template_name = "accounts/login.html"
class GalleryView(LoginRequiredMixin, ListView):
    model = Furn
    template_name = "age/gallery.html"
    def get_context_data(self, **kwargs):
        context = super(GalleryView, self).get_context_data(**kwargs)
        context.update({
            'object_list2': HomeElecApp.objects.filter(user=self.request.user),
            'object_list3': Aniversary.objects.filter(user=self.request.user),
            'object_list4': Other.objects.filter(user=self.request.user),
            'object_list5': Clothes.objects.filter(user=self.request.user),
            'pictures': FurnImage.objects.all(),
            'pictures2': ElecImage.objects.all(),
            'pictures3': AnivImage.objects.all(),
            'pictures4': OtherImage.objects.all(),
            'pictures5': ClothImage.objects.all()
        })
        return context
    def get_queryset(self):
        return Furn.objects.filter(user=self.request.user)
class FurnListView(LoginRequiredMixin,ListView):
    model = Furn
    template_name = "age/list.html"
    def get_context_data(self, **kwargs):
        context = super(FurnListView, self).get_context_data(**kwargs)
        context.update({
            'object_list2': HomeElecApp.objects.filter(user=self.request.user),
            'object_list3': Aniversary.objects.filter(user=self.request.user),
            'object_list4': Other.objects.filter(user=self.request.user),
            'object_list5': Clothes.objects.filter(user=self.request.user),

        })
        return context

    def get_queryset(self):
        return Furn.objects.filter(user=self.request.user)
@login_required
def furnhistory(request,num):
    print(Furn.objects.get(pk=num))
    if request.method == "POST":
        form = FurnHistoryForm(request.POST)
        if form.is_valid():
            historykey = FurnHistory.objects.count() + 1
            form.save()
            print(historykey)
            form2 = FurnHistory.objects.get(pk=historykey)
            form2.mdl=Furn.objects.get(pk=num)
            form2.save()
            return redirect('age:list')
    else:
        form = FurnHistoryForm()

    context = {'form':form}
    return render(request, 'age/historycreate.html', context)
@login_required
def furnimage(request,num):
    print(Furn.objects.get(pk=num))
    if request.method == "POST":
        form = FurnImageForm(request.POST, request.FILES)
        if form.is_valid():
            historykey = FurnImage.objects.count() + 1
            form.save()
            print(historykey)
            form2 = FurnImage.objects.get(pk=historykey)
            form2.mdl=Furn.objects.get(pk=num)
            form2.save()
            return redirect('age:list')
    else:
        form = FurnImageForm()

    context = {'form':form}
    return render(request, 'age/imagecreate.html', context)
class FurnHistoryupdView(LoginRequiredMixin,UpdateView):
    model = FurnHistory
    template_name = "age/historycreate.html"
    fields = ['history1','historyday1']
    def get_success_url(self):
        return reverse_lazy('age:list')
class FurnDetailView(LoginRequiredMixin,DetailView):
    model = Furn
    template_name = "age/homeelec_detail.html"
    def get_context_data(self, **kwargs):
        context = super(FurnDetailView, self).get_context_data(**kwargs)
        context.update({
            'object2': FurnHistory.objects.filter(mdl__pk=self.object.pk),
            'object3': FurnImage.objects.filter(mdl__pk=self.object.pk),
            'type':'furn',
        })
        return context

    def get_queryset(self):
        return Furn.objects.all()
    success_url = reverse_lazy('age:list')

@login_required
def furncreate(request):
    if request.method == "POST":
        form = FurnForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form2 = Furn.objects.get(pk=Furn.objects.all().count())
            form2.user=request.user
            form2.save()
            return redirect('age:list')
    else:
        form = FurnForm()

    context = {'form':form}
    return render(request, 'age/furn_create.html', context)

class FurnDeleteView(LoginRequiredMixin,DeleteView):
    model = Furn
    template_name = "age/homeelec_delete.html"
    success_url = reverse_lazy('age:list')

@login_required
def furnupdate(request,pk):
    if request.method == "POST":
        form = FurnupdForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('age:list')
    else:
        form = FurnupdForm()
    context = {'form':form}
    return render(request, 'age/homeelec_update.html', context)

#家電
@login_required
def elechistory(request,num):
    print(HomeElecApp.objects.get(pk=num))
    if request.method == "POST":
        form = ElecHistoryForm(request.POST)
        if form.is_valid():
            historykey = ElecHistory.objects.count() + 1
            form.save()
            print(historykey)
            form2 = ElecHistory.objects.get(pk=historykey)
            form2.mdl=HomeElecApp.objects.get(pk=num)
            form2.save()
            return redirect('age:list')
    else:
        form = ElecHistoryForm()

    context = {'form':form}
    return render(request, 'age/historycreate.html', context)
@login_required
def elecimage(request,num):
    print(HomeElecApp.objects.get(pk=num))
    if request.method == "POST":
        form = ElecImageForm(request.POST, request.FILES)
        if form.is_valid():
            historykey = ElecImage.objects.count() + 1
            form.save()
            print(historykey)
            form2 = ElecImage.objects.get(pk=historykey)
            form2.mdl=HomeElecApp.objects.get(pk=num)
            form2.save()
            return redirect('age:list')
    else:
        form = ElecImageForm()

    context = {'form':form}
    return render(request, 'age/imagecreate.html', context)
class ElecHistoryupdView(LoginRequiredMixin,UpdateView):
    model = ElecHistory
    template_name = "age/historycreate.html"
    fields = ['history1','historyday1']
    def get_success_url(self):
        return reverse_lazy('age:list')
class HomeelecDetailView(LoginRequiredMixin,DetailView):
    model = HomeElecApp
    template_name = "age/homeelec_detail.html"
    def get_context_data(self, **kwargs):
        context = super(HomeelecDetailView, self).get_context_data(**kwargs)
        context.update({
            'object2': ElecHistory.objects.filter(mdl__pk=self.object.pk),
            'object3': ElecImage.objects.filter(mdl__pk=self.object.pk),
            'type':'elec',
        })
        return context

    def get_queryset(self):
        return HomeElecApp.objects.all()
    success_url = reverse_lazy('age:list')



@login_required
def eleccreate(request):
    if request.method == "POST":
        form = ElecForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form2 = HomeElecApp.objects.get(pk=HomeElecApp.objects.all().count())
            form2.user=request.user
            form2.save()
            return redirect('age:list')
    else:
        form = ElecForm()

    context = {'form':form}
    return render(request, 'age/homeelec_create.html', context)

class HomeelecDeleteView(LoginRequiredMixin,DeleteView):
    model = HomeElecApp
    template_name = "age/homeelec_delete.html"

age/templates/age/foodlist.html
{% extends 'base.html' %}
{% block header %}
    <h1>一覧</h1>
{% endblock header %}
{% block content %}
<h2>食品</h2>
    {% for food in object_list %}
        <p>{{food.foodname}}</p>
        <ul>
            <li><a href="{% url 'age:fooddetail' food.pk%}">詳細画面へ</a></li>
            <li><a href="{% url 'age:foodupdate' food.pk%}" >編集画面へ</a></li>
            <li><a href="{% url 'age:fooddelete' food.pk%}" >削除画面へ</a></li>
        </ul>
    {% endfor %}
    <h2>家電</h2>
    {% for elec in object_list2 %}
        <p>{{elec.HomeElecApp}}</p>
        <ul>
            <li><a href="{% url 'age:homeelecdetail' elec.pk%}">詳細画面へ</a></li>
            <li><a href="{% url 'age:homeelecupdate' elec.pk%}" >編集画面へ</a></li>
            <li><a href="{% url 'age:homeelecdelete' elec.pk%}" >削除画面へ</a></li>
        </ul>
{% endfor %}
    <h2>記念日</h2>
    {% for ani in object_list3 %}
        <p>{{ani.annivapp}}</p>
        <ul>
            <li><a href="{% url 'age:annivdetail' ani.pk%}">詳細画面へ</a></li>
            <li><a href="{% url 'age:annivupdate' ani.pk%}" >編集画面へ</a></li>
            <li><a href="{% url 'age:annivdelete' ani.pk%}" >削除画面へ</a></li>
        </ul>
    {% endfor %}
    <h2>その他</h2>
    {% for otr in object_list4 %}
        <p>{{otr.otherapp}}</p>
        <ul>
            <li><a href="{% url 'age:otherdetail' ani.pk%}">詳細画面へ</a></li>
            <li><a href="{% url 'age:otherupdate' ani.pk%}" >編集画面へ</a></li>
            <li><a href="{% url 'age:otherdelete' ani.pk%}" >削除画面へ</a></li>
        </ul>
    {% endfor %}
    <p><a href="{% url 'age:homeeleccreate' %}" >新規作成画面へ</a></p>
{%endblock content %}

age/templates/age/gallery.html
{% extends 'base.html' %}
{% load imagesize %}
  {% block header %}
    <h1>ギャラリー</h1>
  {% endblock %}
  {% block content %}
{% for image in object_list2%}
   {% with img=image.favorite %}
      {% if image.picture1 %}
         <a href="{% url 'age:homeelecdetail' image.pk%}"><img src='{{ MEDIA_URL }}{{image.picture1}}' width={{ 0 | size:img}} class="galleryimg"></a>
      {% endif %}
      {% for im2 in pictures2 %}
         {% if im2.mdl == image and im2.picture%}
            <a href="{% url 'age:homeelecdetail' image.pk%}"><img src='{{ MEDIA_URL }}{{im2.picture}}' width={{ 0 | size:img}} class="galleryimg"></a>
         {% endif %}
      {% endfor %}
   {% endwith %}
{% endfor %}
{% for image in object_list%}
   {% with img=image.favorite %}
      {% if image.picture1 %}
         <a href="{% url 'age:furndetail' image.pk%}"><img src='{{ MEDIA_URL }}{{image.picture1}}' width={{ 0 | size:img}} class="galleryimg"></a>
      {% endif %}
      {% for im2 in pictures %}
         {% if im2.mdl == image and im2.picture%}
            <a href="{% url 'age:furndetail' image.pk%}"><img src='{{ MEDIA_URL }}{{im2.picture}}' width={{ 0 | size:img}} class="galleryimg"></a>
         {% endif %}
      {% endfor %}
   {% endwith %}
{% endfor %}
{% for image in object_list3%}
   {% with img=image.favorite %}
      {% if image.picture1 %}
         <a href="{% url 'age:anivdetail' image.pk%}"><img src='{{ MEDIA_URL }}{{image.picture1}}' width={{ 0 | size:img}} class="galleryimg"></a>
      {% endif %}
      {% for im2 in pictures3 %}
         {% if im2.mdl == image and im2.picture%}
            <a href="{% url 'age:anivdetail' image.pk%}"><img src='{{ MEDIA_URL }}{{im2.picture}}' width={{ 0 | size:img}} class="galleryimg"></a>
         {% endif %}
      {% endfor %}
   {% endwith %}
{% endfor %}
{% for image in object_list4%}
   {% with img=image.favorite %}
      {% if image.picture1 %}
         <a href="{% url 'age:fashiondetail' image.pk%}"><img src='{{ MEDIA_URL }}{{image.picture1}}' width={{ 0 | size:img}} class="galleryimg"></a>
      {% endif %}
      {% for im2 in pictures4 %}
         {% if im2.mdl == image and im2.picture%}
            <a href="{% url 'age:fashiondetail' image.pk%}"><img src='{{ MEDIA_URL }}{{im2.picture}}' width={{ 0 | size:img}} class="galleryimg"></a>
         {% endif %}
      {% endfor %}
   {% endwith %}
{% endfor %}
{% for image in object_list5%}
   {% with img=image.favorite %}
      {% if image.picture1 %}
         <a href="{% url 'age:otherdetail' image.pk%}"><img src='{{ MEDIA_URL }}{{image.picture1}}' width={{ 0 | size:img}} class="galleryimg"></a>
      {% endif %}
      {% for im2 in pictures5 %}
         {% if im2.mdl == image and im2.picture%}
            <a href="{% url 'age:otherdetail' image.pk%}"><img src='{{ MEDIA_URL }}{{im2.picture}}' width={{ 0 | size:img}} class="galleryimg"></a>
         {% endif %}
      {% endfor %}
   {% endwith %}
{% endfor %}
<p><a href="{% url 'age:homeeleccreate' %}" class="txtbtn">新規作成画面へ</a></p>
{%endblock content %}

age/templates/age/homeelec_detail.html
{% extends 'base.html' %}
{% load age %}
{% load static%}
{% block header %}
{% if object.picture1 %}
   <img src='{{ MEDIA_URL }}{{object.picture1}}' width=1300 class="thumbnail">
{%else %}
   {% with img="img/"|addstr:type|addstr:"-background.svg" %}
         <img src="{% static img %}" width=1300 class="thumbnail">
   {% endwith %}
{% endif %}
{% if type == 'aniv' %}
<h1 class="thingstitle">{{ object.annivapp }}</h1>
{% else %}
<h1 class="thingstitle">{{ object.name }}</h1>
{% endif %}
{% endblock %}
{% block content %}
{% if type == 'furn' %}
   <p><a href="{% url 'age:furnupdate' object.pk%}" >
{% elif type == 'elec' %}
   <p><a href="{% url 'age:homeelecupdate' object.pk%}" >
{% elif type == 'aniv' %}
   <p><a href="{% url 'age:anivupdate' object.pk%}" >
{% elif type == 'fashion' %}
   <p><a href="{% url 'age:fashionupdate' object.pk%}" >
{% elif type == 'other' %}
   <p><a href="{% url 'age:otherupdate' object.pk%}" >
{% endif %}
<img src="{% static 'img/edit.svg' %}" width=50 alt="編集" class="editbtn"></a></p>
{% if type == 'furn' %}
   <p><a href="{% url 'age:furndelete' object.pk%}" >
{% elif type == 'elec' %}
   <p><a href="{% url 'age:homeelecdelete' object.pk%}" >
{% elif type == 'aniv' %}
   <p><a href="{% url 'age:anivdelete' object.pk%}" >
{% elif type == 'fashion' %}
   <p><a href="{% url 'age:fashiondelete' object.pk%}" >
{% elif type == 'other' %}
   <p><a href="{% url 'age:otherdelete' object.pk%}" >
{% endif %}
<img src="{% static 'img/delete.svg' %}" width=50 alt="削除" class="deletebtn"></a></p>
{% if type == 'aniv' %}
<p>記念日が起こってから :  <span class="detailage">{{ 0 | showage:object.didday}}年</span></p>
{% else %}
<h3 class="detailage">{{ 0 | showage:object.birthday}}歳</h3>
{% endif %}
{% if type == 'aniv' %}
<p>記念日が起こった日付：{{object.didday}}</p>
{% else %}
<p>誕生日：{{object.birthday}}</p>
{% endif %}
<p>大事度：{{object.favorite}}</p>
<p>ストーリー：{{ object.story }}</p>
{% if object.category %}
   <p class="float">カテゴリ：</p>
   {% if type == 'furn' %}
   <div class="furntag">
   {% elif type == 'elec' %}
      <div class="electag">
   {% elif type == 'aniv' %}
      <div class="anivtag">
   {% elif type == 'fashion' %}
      <div class="clothtag">
   {% elif type == 'other' %}
      <div class="othertag">
   {% endif %}
      {% with img="img/"|addstr:object.category|addstr:".svg" %}
          <img src="{% static img %}" width=30 class="category">
      {% endwith %}
      <p>{{ object.category }}
   </p></div>
{% endif %}
<h3 class="float-clear">画像</h3>
{% if object.picture1 %}
   <img src='{{ MEDIA_URL }}{{object.picture1}}' width=100 class="imgradius">
{% endif %}
{% for object3 in object3 %}
{% if object3.picture %}
{% with link="age:"|addstr:type|addstr:"image" %}
   <a href="{% url link object.pk%}" ><img src='{{ MEDIA_URL }}{{object3.picture}}' width=100 class="imgradius"></a>
{% endwith %}
{% endif %}
{% endfor %}
{% with link="age:"|addstr:type|addstr:"image" %}
   <a href="{% url link object.pk%}"><img src="{% static 'img/add-square.svg' %}" width=100 alt="画像を追加" class="imgradius"></a>
{% endwith %}
<h3>ヒストリー</h3>
{% for object2 in object2 %}
{% if object2 %}
   {% if forloop.counter != 1%}
   <img src="{% static 'img/history.svg' %}" width=20 class="dot">
   <br>
   {% endif %}
   <div class="history">
   <p>{{object2.historyday1}}&nbsp &nbsp{{object2.history1}}</p>
   {% with link="age:"|addstr:type|addstr:"historyupd" %}
      <a href="{% url link object2.pk%}" ><img src="{% static 'img/historyedit.svg' %}" width=40 alt="ヒストリーを編集"></a>
   {% endwith %}
   </div>
{% endif %}
{% endfor %}
<br>
{% with link="age:"|addstr:type|addstr:"history" %}
   <p><a href="{% url link object.pk%}" class="txtbtn">ヒストリーを追加</a></p>
{% endwith %}
{% endblock%}

age/templates/age/index.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<center>
<div class="titlesmn">
    <img src="{% static 'img/logo-brown.svg' %}" alt = "AGE" height= "200">
    <h1>-ものの年齢記録アプリ-</h1>
</div>
</center>
{% endblock header %}
{% block content %}
<center>
    <p>大事な家電も、買ってきたご飯の材料も、忘れられない思い出も。なんでも年齢"を記録しよう</p>
    <div class="titlebtn">
    <a href="{% url 'age:signup' %}">アカウント新規作成</a>
    <a href="URL">ログイン</a>
    </div>
</center>
{%endblock content %}